### ISSUE TITLE
license

### ISSUE THREAD

**Issue by TNTwise** [TArdelean/DynamicConvolution#12]
Thank you for your work on this. I am wanting to use this code provided in a project, but cannot do so as there is no license in this project. Is this intentional? if not can you provide a license to allow this code to be distributed elsewhere?

Thank you for your time.

**Comment by TArdelean** [comment]
Hello, thank you for the interest in this work. I've added an MIT License to the repository; feel free to use the code in your project!

**Comment by TNTwise** [comment]
Thank you!
